name: CI-CD Pipeline
 
on:
  workflow_dispatch:
 
jobs:
 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only needs to read code
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
 
      - name: Lint JavaScript
        run: npx eslint javascript.js || true
 
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=vsh4535-cyber_CICD
            -Dsonar.organization=vsh4535-cyber
        env:
          SONAR_TOKEN: ${{ secrets.CICD_token }}
          SONAR_HOST_URL: https://sonarcloud.io
 
      - name: Build
        run: |
          mkdir devops
          cp index.html devops/
          cp style.css devops/
          cp javascript.js devops/
 
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: devops/
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write       
      id-token: write    
 
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
