name: CI-CD Pipeline v2
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only needs to read code
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
 
      - name: Lint JavaScript
        run: npx eslint javascript.js || true
 
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=vsh4535-cyber_CICD
            -Dsonar.organization=vsh4535-cyber
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
 
      - name: Build
        run: |
          mkdir temp
          cp index.html temp/
          cp styles.css temp/
          cp script.js temp/
 
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: temp/
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write       # Needed to deploy
      id-token: write    # Required for secure OIDC auth
 
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4